name: Tests

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ "2.3.7", "2.4.10", "2.5.9", "2.6.8", "2.7.4", "3.0.6", "3.1.4", "3.2.2", "jruby-9.2", "jruby-9.3", "jruby-9.4" ]
        include:
          - ruby: "2.3.7"
            bundler-version: '2.3.26'
          - ruby: "2.4.10"
            bundler-version: '2.3.26'
          - ruby: "2.5.9"
            bundler-version: '2.3.26'
          - ruby: "2.6.8"
            bundler-version: '2.4.12'
          - ruby: "2.7.4"
            bundler-version: '2.4.12'
          - ruby: "3.0.6"
            bundler-version: '2.4.12'
          - ruby: "3.1.4"
            bundler-version: '2.4.12'
          - ruby: "3.2.2"
            bundler-version: '2.4.12'
          - ruby: "jruby-9.2"
            bundler-version: '2.3.26'
          - ruby: "jruby-9.3"
            bundler-version: '2.3.26'
          - ruby: "jruby-9.4"
            bundler-version: '2.3.26'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: |
        gem update --system 3.2.3
        gem install bundler -v ${{ matrix.bundler-version }}
        bundle install --jobs=3
    - name: Run tests (MRI)
      run: bundle exec rake spec
      if: "!startsWith(matrix.ruby, 'jruby')"
    - name: Run tests (JRuby)
      run: JRUBY_OPTS=--debug bundle exec rake spec
      if: startsWith(matrix.ruby, 'jruby')
