name: Tests

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ "2.3.7", "2.4.10", "2.5.9", "2.6.8", "2.7.4", "3.0.6", "3.1.4", "3.2.2", "jruby-9.2", "jruby-9.3", "jruby-9.4" ]
        include:
          - ruby: "2.3.7"
            requires-older-rubygems: true
            requires-older-bundler: true
          - ruby: "2.4.10"
            requires-older-rubygems: true
            requires-older-bundler: true
          - ruby: "jruby-9.2"
            requires-older-bundler: true
          - ruby: "jruby-9.3"
            requires-older-bundler: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - if: ${{ matrix.requires-older-rubygems }}
      run: gem update --system 3.2.3
    - if: ${{ matrix.requires-older-bundler }}
      run: gem install bundler -v 2.3.26
    - name: Bundle install
      run: bundle install --jobs=3
    - name: Run tests (MRI)
      run: bundle exec rake spec
      if: "!startsWith(matrix.ruby, 'jruby')"
    - name: Run tests (JRuby)
      run: JRUBY_OPTS=--debug bundle exec rake spec
      if: startsWith(matrix.ruby, 'jruby')
